name: AWS API Calls

on: [push]

jobs:
  run-cli-command:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: ${{ secrets.ROLE_DURATION }}
          aws-region: ${{ secrets.AWS_REGION}}
      - name: Log start
        run: echo logging into aws with OIDC
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1